name: Workflow - Release
on:
  release:
    types: [published]
jobs:
  build_docker_images:
    name: Build Docker Images
    permissions:
      packages: write
    uses: ./.github/workflows/docker.yml
